### ISSUE TITLE
SEB on mac: (may need to be placed on numbas project)

### ISSUE THREAD

**Issue by Spruce8913** [numbas/numbas-lti-provider#282] opened 2023-09-15 11:17 UTC
After a numbas exam within Safe Exam Browser, the results page keeps scrolling back up (presumably to bring the green notification bar (about the attempt being saved successfully) in focus). This prevents (easy) access to review mode of some questions.

It only happened on some macbooks, I could not diagnose a consistent pattern for example about mac version.

**Comment by christianp** [comment] 2023-10-04 16:49
Sorry, I can't reproduce this. There's no explicit code that would scroll back up to the top on the results page, as far as I can remember.
I'm going to close this, but please reopen it if it happens again and you can give any more detail.

**Closed by christianp** 2023-10-04 16:49 UTC
